# Generated by Django 4.2.20 on 2025-05-13 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hip_hop', 'Hip Hop'), ('electronic', 'Electronic'), ('country', 'Country'), ('r_and_b', 'R&B'), ('indie', 'Indie'), ('other', 'Other')], default='other', max_length=20)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('audio_file', models.FileField(upload_to='music/')),
                ('cover_image', models.ImageField(default='covers/default.jpg', upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='users.artist')),
            ],
            options={
                'verbose_name_plural': 'Music',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('music', models.ManyToManyField(related_name='playlists', to='music_app.music')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
