# Generated by Django 4.2.20 on 2025-05-15 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_music_genre_listeninghistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_favorites', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('total_duration_played', models.DurationField(default=datetime.timedelta(0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('music', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='music_app.music')),
            ],
            options={
                'verbose_name_plural': 'Music Statistics',
            },
        ),
    ]
